uint64 timestamp            #tiempo desde el inicio del sistema (microsegundos)
uint64 timestamp_sample     #el tiempo del dato sin procesar (microsegundos)
uint16 pila                 #info--
uint16 stack_voltage        #info1--
uint16 load_currente        #info2--
uint16 power                #info3--
uint16 energy               #info4--
uint16 battery_voltage      #info5--
uint16 battery_current      #info6--
uint16 load_voltage         #info7--
uint16 temp1                #info8--
uint16 temp2                #info9--
uint16 temp3                #info10--
uint16 temp4                #info11--
uint16 target_temp          #info12
uint16 board_temp           #info13--
uint16 h2_pressure          #info14--
uint16 fan_speed            #info15--
uint16 state                #info16
uint16 signo
uint16 top_temp

# TOPICS fuelcellbatt
